### ISSUE TITLE
Example Streaming not working in iOS

### ISSUE THREAD

**Issue by jBachalo** [watson-developer-cloud/unity-sdk#572] opened 2019-05-08 19:42 UTC
Running the Example Streaming demo in the editor (2019.1, Mac) works fine so I know my iAM authentication is correct.
However cannot get to work after deploying to my iPhone.

This is the complete XCode console message, I can see a time out and further on a credentials error

https://pastebin.com/NZ5PLUpC

**Comment by mediumTaj** [comment] 2019-05-08 20:14
Duplicate of https://github.com/watson-developer-cloud/unity-sdk/issues/566

Please comment on that issue if it deals with iOS authentication.

**Closed by mediumTaj** 2019-05-08 20:14 UTC
Labels: duplicate

**Comment by jBachalo** [comment] 2019-05-08 20:19
Thanks but not sure whether it is an iOS authentication specific issue. If you have time to view my paste bin you could probably get a better idea what is happening.

**Comment by mediumTaj** [comment] 2019-05-08 20:31
It's the same error as #566 
```
Exception: System.NotSupportedException: System.Reflection.Emit.DynamicMethod
```
